# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$aws\
$gcloud\
$openstack\
$azure\
$env_var\
$crystal\
$custom\
$sudo\
$fill\
$nodejs\
$cmd_duration\
$jobs\
$memory_usage\
$time\
$line_break\
$character"""

[aws]
format = '[$symbol$profile ($region)]($style) '
symbol = '󰸏 '
style = 'yellow'

[cmd_duration]
format = '[⌛️$duration ]($style)'
style = "bold bright-yellow"

[fill]
symbol = ' '
style = 'bold green'

[git_branch]
style = 'bold purple'
symbol = ' '

[memory_usage]
disabled = true
format = '[$symbol$ram( | $swap)]($style) '
symbol = '󰍛 '
style = 'dimmed white'
threshold = -1

[nodejs]
format = "[$symbol($version) ]($style)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[time]
disabled = false
format = '[$time]($style)'
style = "dimmed white"
time_format = '%T'

