# https://alacritty.org/config-alacritty.html

import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
option_as_alt = "Both"
padding.x = 8
padding.y = 8

[font]
normal.family = "FiraCode Nerd Font"
size = 20