# https://alacritty.org/config-alacritty.html

[general]
import = [
    "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
blur = true
decorations = "Buttonless"
opacity = 0.85
option_as_alt = "Both"
padding.x = 8
padding.y = 8
startup_mode = "Maximized"

[font]
normal.family = "FiraCode Nerd Font"
size = 18